Python. Homework #2. Task #2 Порсев Егор
Furetur/PythonProgramming pull request #4
Opened 2021-03-06 16:51 UTC by Furetur

2021-03-09 13:17 UTC, nbirillo requested changes
Great! Thank you a lot for the tests!

2021-03-09 13:17 UTC, nbirillo commented on hw2/memoize.py
> +    return tuple((k, v) for k, v in dictionary.items())
Should we sort `items` since it is a dictionary? I could be wrong, but we can get a different order for items depending on the different things.

2021-03-09 13:17 UTC, nbirillo commented on hw2/memoize.py
> +@dataclass(frozen=True)
Great!

2021-03-09 16:05 UTC, Furetur commented on hw2/memoize.py
> +    return tuple((k, v) for k, v in dictionary.items())
Thanks! That's a really nasty potential bug, it would be probably hard to find :)

2021-03-10 08:35 UTC, nbirillo approved these changes
Great, thanks!

2021-03-10 08:35 UTC, merged